name: Go API

on:
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    run-on: ubuntu-latest
  steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with: go-version: "1.24"
    
    - name: Download Dependencies
      uses: go mod tidy

    - name: Build Project
      run: go build ./...

    - name: Run Tests
      run: go test ./...
